import { PlatformId, PlatformInfo } from "../types/plugin.js";

export const PLATFORMS: PlatformInfo[] = [
  {
    id: "chatgpt",
    name: "ChatGPT",
    description:
      "Connect via Streamable HTTP Remote MCP Server in Developer Mode / Workspace Actions.",
    badge: "Remote HTTPS MCP",
    icon: "chatgpt",
    supported: true,
    connectionType: "mcp_remote",
    transport: "streamable_http",
    requiresRemoteServer: true,
    requiresAuthentication: false,
    requiresManualSetup: true,
    docsUrl: "/docs#chatgpt",
    officialDocs: "https://platform.openai.com/docs/actions",
  },
  {
    id: "claude",
    name: "Claude Desktop",
    description:
      "Standard stdio sub-process configuration for Anthropic's Claude Desktop application.",
    badge: "Native stdio",
    icon: "claude",
    supported: true,
    connectionType: "mcp_stdio",
    transport: "stdio",
    requiresRemoteServer: false,
    requiresAuthentication: false,
    requiresManualSetup: true,
    docsUrl: "/docs#claude",
    officialDocs: "https://modelcontextprotocol.io/quickstart/user",
  },
  {
    id: "gemini",
    name: "Google Gemini",
    description: "Function-calling tool declarations and Gemini SDK / CLI adapter integration.",
    badge: "Function Calling",
    icon: "gemini",
    supported: true,
    connectionType: "adapter",
    transport: "function_calling",
    requiresRemoteServer: false,
    requiresAuthentication: false,
    requiresManualSetup: true,
    docsUrl: "/docs#gemini",
    officialDocs: "https://ai.google.dev/docs/function_calling",
  },
  {
    id: "cursor",
    name: "Cursor IDE",
    description:
      "stdio sub-process integration via `.cursor/mcp.json` for AI-assisted code editors.",
    badge: "IDE stdio",
    icon: "cursor",
    supported: true,
    connectionType: "mcp_stdio",
    transport: "stdio",
    requiresRemoteServer: false,
    requiresAuthentication: false,
    requiresManualSetup: true,
    docsUrl: "/docs#manual",
    officialDocs: "https://docs.cursor.com/context/model-context-protocol",
  },
  {
    id: "windsurf",
    name: "Windsurf",
    description: "Native MCP stdio server integration for Codeium Windsurf Cascade editor.",
    badge: "IDE stdio",
    icon: "windsurf",
    supported: true,
    connectionType: "mcp_stdio",
    transport: "stdio",
    requiresRemoteServer: false,
    requiresAuthentication: false,
    requiresManualSetup: true,
    docsUrl: "/docs#manual",
    officialDocs: "https://codeium.com/windsurf",
  },
  {
    id: "mcp-cli",
    name: "Generic MCP Client",
    description:
      "Standard JSON-RPC 2.0 over stdio or Streamable HTTP for any MCP-compliant client.",
    badge: "JSON-RPC 2.0",
    icon: "terminal",
    supported: true,
    connectionType: "manual",
    transport: "streamable_http_or_stdio",
    requiresRemoteServer: false,
    requiresAuthentication: false,
    requiresManualSetup: true,
    docsUrl: "/docs#manual",
    officialDocs: "https://modelcontextprotocol.io",
  },
];

export function getPlatformById(id: PlatformId): PlatformInfo | undefined {
  return PLATFORMS.find((p) => p.id === id);
}
